(function($){APF({group:"FBA",name:"InboundQueue",plugins:["APF.Plugin.Loading"],initialize:function(){APF.setAttr("shipments",new FBA.Core.Collection.Shipments());
APF.setAttr("plans",new FBA.Core.Collection.Manifests());
APF.setAttr("searchshipments",new FBA.Core.Collection.SearchShipments());
APF.bind("start:after",function(){APF.setAttr("inboundPerformance",new FBA.Core.View.InboundPerformance());
});
}});
}(jQuery));
(function($){$.extend(FBA.InboundQueue.Router,{routes:{"shipments-search/*searchQueryMap":{name:"shipments-search",view:"FBA.InboundQueue.View.SearchShipmentController",searchQueryMap:["searchQueryMap"]},"shipments/*query":{name:"shipments-query",view:"FBA.InboundQueue.View.ShipmentController",query:["orderBy","isOrderAscending","statusFilter","dateRange","lastUpdatedAfter","lastUpdatedBefore"]},"shipments":{name:"shipments",view:"FBA.InboundQueue.View.ShipmentController"},"plans/*query":{name:"manifests-query",view:"FBA.InboundQueue.View.ManifestController",query:["orderBy","isOrderAscending","statusFilter"]},"plans":{name:"manifests",view:"FBA.InboundQueue.View.ManifestController"},"*query":{name:"default-shipments",view:"FBA.InboundQueue.View.ShipmentController",query:["orderBy","isOrderAscending","statusFilter","dateRange","lastUpdatedAfter","lastUpdatedBefore"]}},parseArg:{orderBy:function(value){return(!value?"LAST_UPDATE_DATE":value);
},isOrderAscending:function(value,data,actionData){var orderBy=data.orderBy||action.orderBy;
if(value!==true&&value!==false){if(orderBy=="LAST_UPDATE_DATE"){return false;
}else{return false;
}}return value;
},statusFilter:function(value){if(!value){return;
}if(value=="ALL"){value="";
}return value;
},searchQueryMap:function(value){return{"All":[value]};
},lastUpdatedBefore:function(value){return this.date(value);
},lastUpdatedAfter:function(value){return this.date(value);
},date:function(value){if(!value){return;
}if($.datepicker.fadedDateFormat.match(/\./)){return value.replace(/-/g,".");
}return value.replace(/-/g,"/");
}},encodeArg:{statusFilter:function(value){return value;
},lastUpdatedBefore:function(value){return this.date(value);
},lastUpdatedAfter:function(value){return this.date(value);
},date:function(value){if(!value){return;
}return value.replace(/\//g,"-").replace(/\./g,"-");
}}});
}(jQuery));
(function($){$.extend(FBA.InboundQueue.Html,{tableSortableHeaderTemplate:_.template($("#fba-inbound-queue-table-header-sortable").html()),genericStatusFilterTemplate:_.template($("#fba-inbound-queue-status-filter").html()),statuses:{manifests:["ALL","working"],shipments:["ALL","working","inTransit","atFulfillmentCenter","closed","deletedCancelled"]},defaultText:{manifests:"search-by-plan-id",shipments:"search-by-shipment-id"},defaultSortOrder:{LAST_UPDATE_DATE:"desc",CREATE_DATE:"desc"},isOrderedBy:function(orderName){return(APF.getData().orderBy==orderName);
},isAscending:function(orderName){return(APF.getData().isOrderAscending||false);
},isAscendingByThis:function(orderName){return this.isOrderedBy(orderName)?this.isAscending(orderName):(this.defaultSortOrder[orderName]?true:false);
},getStatusFilters:function(data,tableType){var statuses=this.statuses[tableType];
var dataCopy=_.clone(data);
var filters=[];
var showFilter=true;
_(statuses).each(function(status){dataCopy.statusFilter=status;
var url=APF.getUrl(dataCopy);
var name=APF.strings[status];
var classes=(data.statusFilter===status)?"current":"";
if(!APF.getData().statusFilter&&status==="ALL"){classes="current";
}filters.push({url:url,name:name,classes:classes});
});
if(tableType=="searchshipments"){showFilter=false;
}return this.genericStatusFilterTemplate({filters:filters,showFilter:showFilter,defaultText:APF.getAttr("hasGenericShipmentSearch")?APF.strings["search-by-shipment-attr"]:APF.strings[this.defaultText[tableType]]});
},sortableTableHeader:function(data,key,name,headerClasses){var dataCopy=_.clone(data);
_.extend(dataCopy,{orderBy:key,isOrderAscending:!this.isAscendingByThis(key)});
var url=APF.getUrl(dataCopy);
var classes="";
if(this.isOrderedBy(key)){classes+="sort-current ";
classes+=this.isAscending(key)?"sort-asc":"sort-desc";
}else{classes+="sort-"+(this.defaultSortOrder[key]||"asc");
}return this.tableSortableHeaderTemplate({url:url,name:name,classes:classes,headerClasses:headerClasses||""});
}});
}(jQuery));
(function($){FBA.InboundQueue.Model.CSM=APF.Model.Base.extend({initialize:function(options){this.requestId=options.requestId;
this.canTrackCSM=true;
APF.Model.Base.prototype.initialize.call(this,options);
},trackCSM:function(funcName){if(this.canTrackCSM){APF.Util.CSM[funcName].apply(APF.Util.CSM,_.rest(arguments,1));
}},start:function(scope){this.scope=scope;
this.trackCSM("start",this.scope);
},response:function(requestId){this.requestId=requestId||this.requestId;
this.trackCSM("response",this.requestId,this.scope);
},criticalFeature:function(){this.trackCSM("criticalFeature",this.scope);
},stop:function(){this.trackCSM("stop",this.scope);
this.canTrackCSM=false;
}});
}(jQuery));
(function($){FBA.InboundQueue.View.Layout=APF.View.Layout.extend({initialize:function(options){this.el=$(this.el);
this.options=options;
this.data=options.data;
this.el.html(_.template($(this.templateName).html())());
this.layout={"#fba-inbound-queue-controller":[this.controllerName]};
APF.View.Layout.prototype.initialize.call(this,options);
},enter:function(){this.renderContinueBtn();
var events={"submit     #fba-inbound-queue-search-by-id-form":"search","focus      #fba-inbound-queue-search-by-id":"clearDefaultText","blur       #fba-inbound-queue-search-by-id":"restoreDefaultText","click      #fba-inbound-queue-filters":"filterResults","change     #fba-inbound-queue-date-dropdown":"selectDate","submit     #fba-inbound-queue-date-form":"submitDateFilter"};
Backbone.View.prototype.delegateEvents.call(this,events);
APF.View.Layout.prototype.enter.call(this);
},renderContinueBtn:function(){if($("#fba-core-page-action-secondary").length>0){return;
}var cartManifest=new FBA.Core.Model.CartManifest();
cartManifest.fetch({success:function(model,resp){if(resp.data){var manifest=new FBA.Core.Model.Manifest(resp.data);
var btnTemplate=_.template($("#fba-inbound-queue-template-continue-plan-button").html())({manifest:manifest});
$("#fba-inbound-queue-continue-plan-container").html(btnTemplate);
}}});
},filterResults:function(e){var target=$(e.target);
if(target.is(":radio")){target.attr("checked",true);
APF.Util.loadUrl(target.val());
}else{return;
}},search:function(e){e.preventDefault();
var that=this;
var searchEl=$("#fba-inbound-queue-search-by-id",this.el);
var result=this.collection.get(searchQuery);
var searchQuery=$.trim(searchEl.val());
if(searchQuery==""||searchQuery==searchEl.attr("data-defaultText")){return false;
}if(this.idAttribute=="shipmentId"&&APF.getAttr("hasGenericShipmentSearch")){window.location="#shipments-search/"+searchQuery;
return;
}if(this.popOverSearch){this.popOverSearch.hide();
}this.popOverSearch=new APF.View.Popover({locationElement:searchEl,location:"bottom",literalContent:$("#fba-inbound-queue-content-loading").html(),width:"700"});
this.popOverSearch.render();
var contentContainer=this.popOverSearch.el;
var showResult=function(model){if(!model.get("name")){that.popOverSearch.hide();
return;
}contentContainer.html(_.template($("#fba-inbound-queue-template-search-result").html())({model:model}));
};
if(result){showResult(result);
}else{result=new this.collection.model();
var reqId={};
reqId[this.idAttribute]=searchQuery;
result.fetch({data:reqId,success:showResult});
}},removeLoading:function(){$(".fba-inbound-queue-loading-sm",this.el).remove();
},clearDefaultText:function(){var searchEl=$("#fba-inbound-queue-search-by-id",this.el);
if(searchEl.attr("data-defaultText")==searchEl.attr("value")){searchEl.attr("value","");
searchEl.removeClass("label");
}},restoreDefaultText:function(){var searchEl=$("#fba-inbound-queue-search-by-id",this.el);
if($.trim(searchEl.val())==""){searchEl.attr("value",searchEl.attr("data-defaultText"));
searchEl.addClass("label");
}},removeDatePickers:function(){var fromDate=$("#fba-inbound-queue-from-date",this.el);
var toDate=$("#fba-inbound-queue-to-date",this.el);
fromDate.datepicker("destroy");
toDate.datepicker("destroy");
},setDateFilters:function(){var dateDropdown=$("#fba-inbound-queue-date-dropdown",this.el);
var fromDate=$("#fba-inbound-queue-from-date",this.el);
var toDate=$("#fba-inbound-queue-to-date",this.el);
var data=APF.getData();
if(this.idAttribute!="shipmentId"){$("#fba-core-date-filters",this.el).hide();
}this.setDatePickers();
if(data.dateRange){dateDropdown.val(data.dateRange);
}else{dateDropdown.val("");
}if(dateDropdown.val()!="custom"){$("#fba-inbound-queue-date-boxes",this.el).hide();
}$("#fba-inbound-queue-to-error",this.el).hide();
$("#fba-inbound-queue-from-error",this.el).hide();
$("#fba-inbound-queue-order-error",this.el).hide();
},setDatePickers:function(){var fromDate=$("#fba-inbound-queue-from-date",this.el);
var toDate=$("#fba-inbound-queue-to-date",this.el);
var data=APF.getData();
fromDate.datepicker({constrainInput:true,maxDate:+0});
toDate.datepicker({constrainInput:true,maxDate:+0});
if(data.lastUpdatedAfter){fromDate.val(data.lastUpdatedAfter);
}if(data.lastUpdatedBefore){toDate.val(data.lastUpdatedBefore);
}},selectDate:function(){var fromDate=$("#fba-inbound-queue-from-date",this.el);
var toDate=$("#fba-inbound-queue-to-date",this.el);
var dateBoxes=$("#fba-inbound-queue-date-boxes",this.el);
var days=$("#fba-inbound-queue-date-dropdown",this.el).val();
var initialDateRange=APF.getData().dateRange;
if(!isNaN(days)){dateBoxes.hide();
fromDate.datepicker("setDate",-days);
toDate.datepicker("setDate","null");
if(days!=initialDateRange){this.filterDates();
}}else{if(days=="custom"){dateBoxes.show();
}else{fromDate.val("");
toDate.val("");
dateBoxes.hide();
if(initialDateRange&&(initialDateRange!="all")){this.filterDates();
}}}},submitDateFilter:function(e){e.preventDefault();
this.filterDates();
},filterDates:function(){if(!this.validate()){return;
}var dateDropdown=$("#fba-inbound-queue-date-dropdown",this.el);
var fromDate=$("#fba-inbound-queue-from-date",this.el);
var toDate=$("#fba-inbound-queue-to-date",this.el);
var data=APF.getData();
data.dateRange=dateDropdown.val();
if(!isNaN(data.dateRange)){fromDate.datepicker("setDate",-(data.dateRange));
toDate.datepicker("setDate","null");
}if(data.dateRange!="all"){var fromDateVal=$.trim(fromDate.val());
var toDateVal=$.trim(toDate.val());
data.lastUpdatedAfter=(fromDateVal?fromDateVal:"");
data.lastUpdatedBefore=(toDateVal?toDateVal:"");
}else{data.lastUpdatedAfter="";
data.lastUpdatedBefore="";
}APF.Util.loadUrl(APF.getUrl(data));
},validate:function(){var dateDropdown=$("#fba-inbound-queue-date-dropdown",this.el);
var fromDate=$("#fba-inbound-queue-from-date",this.el);
var toDate=$("#fba-inbound-queue-to-date",this.el);
var fromError=$("#fba-inbound-queue-from-error",this.el);
var toError=$("#fba-inbound-queue-to-error",this.el);
var orderError=$("#fba-inbound-queue-order-error",this.el);
var dateFormat=new RegExp($.datepicker.dateRegularExpression);
var strings=APF.strings;
var valid=true;
var msg="";
if(dateDropdown.length>0&&dateDropdown.val()!="all"){if(!dateFormat.test(fromDate.val())){fromDate.addClass("fba-core-input-error");
fromError.show();
valid=false;
}else{fromDate.removeClass("fba-core-input-error");
fromError.hide();
}if(!dateFormat.test(toDate.val())){toDate.addClass("fba-core-input-error");
toError.show();
valid=false;
}else{toDate.removeClass("fba-core-input-error");
toError.hide();
}}if(fromDate.datepicker("getDate")>toDate.datepicker("getDate")){fromDate.addClass("fba-core-input-error");
toDate.addClass("fba-core-input-error");
orderError.show();
valid=false;
}else{orderError.hide();
}if(valid){fromDate.removeClass("fba-core-input-error");
toDate.removeClass("fba-core-input-error");
}return valid;
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ManifestController=APF.View.Controller.extend({useData:[],initialize:function(options){this.el=$("#fba-inbound-queue-page");
APF.View.Controller.prototype.initialize.call(this,options);
},getMap:function(){return{view:"FBA.InboundQueue.View.ManifestsLayout"};
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ShipmentController=APF.View.Controller.extend({useData:[],initialize:function(options){this.el=$("#fba-inbound-queue-page");
APF.View.Controller.prototype.initialize.call(this,options);
},getMap:function(){return{view:"FBA.InboundQueue.View.ShipmentsLayout"};
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ShipmentsController=APF.View.Controller.extend({waitForRender:true,controls:"fba-inbound-queue-controller-page",getMap:function(){var shipments=APF.getAttr("shipments");
var el=this.el;
if(this.state.data.page===undefined){el.find(".fba-core-data").html($("#fba-inbound-queue-content-loading").html());
el.find(".fba-core-data-pagination").html("");
shipments.reset();
}return{view:"FBA.InboundQueue.View.ShipmentCollection",collection:shipments};
APF.View.Controller.prototype.getMap.call(this);
},initialize:function(options){this.parent=options.parent;
APF.View.Controller.prototype.initialize.call(this);
this.bind("render",this.initDateFilters,this);
},exit:function(){this.parent.removeDatePickers();
APF.View.Controller.prototype.exit.call(this);
},initDateFilters:function(){this.parent.setDateFilters();
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ShipmentCollection=APF.View.Collection.extend({view:"FBA.InboundQueue.View.Shipment",container:"#fba-inbound-queue-shipments-collection",templates:{layout:"#fba-inbound-queue-template-shipments-collection"},initialize:function(options){this.appCSM=APF.getAttr("appCSM");
this.shipmentsCSM=new FBA.InboundQueue.Model.CSM();
this.isExtraInfoRendered={shipmentCarrier:false,defectStatus:false};
options.data.pageName="fba-shipping-queue";
APF.View.Collection.prototype.initialize.call(this,options);
},enter:function(events){this.collection.bind("render:after",this.trackCriticalFeature,this);
this.collection.bind("extraInfoRender:after",this.trackStop,this);
APF.View.Collection.prototype.enter.call(this,events);
},exit:function(){this.collection.unbind("render:after",this.trackCriticalFeature,this);
this.collection.unbind("extraInfoRender:after",this.trackStop,this);
APF.View.Collection.prototype.exit.call(this);
},trackCriticalFeature:function(){this.appCSM.criticalFeature();
this.shipmentsCSM.criticalFeature();
},trackStop:function(){var canStop=true;
$.each(this.isExtraInfoRendered,function(attribute,value){if(!value){canStop=false;
return false;
}});
if(canStop){this.appCSM.stop();
this.shipmentsCSM.stop();
}},getTemplateData:function(data,model,collection){return{data:data,totalQuantity:this.collection.totalRecords,dataPagination:{index:data.index||0,pageSize:collection.data.pageSize,totalRecords:collection.data.totalRecords}};
},loadCollectionData:function(){this.appCSM.start("FBA-InboundQueue-App-Shipments");
this.shipmentsCSM.start("FBA-InboundQueue-Shipments");
APF.View.Collection.prototype.loadCollectionData.call(this);
},setCollectionData:function(response){this.appCSM.response();
this.shipmentsCSM.response(this.collection.requestId);
APF.View.Collection.prototype.setCollectionData.call(this,response);
this.parent.options.parent.removeLoading();
this.getCarrierInfo();
this.getDefectAcknowledgementInfo();
this.getFlatFileInfo();
},getCarrierInfo:function(){var callback=this.getModelMapper("shipmentCarrier","carrier");
this.collection.fetchCarrierShipments({callback:callback});
},getDefectAcknowledgementInfo:function(){var callback=this.getModelMapper("defectStatus","defects");
this.collection.fetchDefectAcknowledgementStatus({callback:callback});
},getFlatFileInfo:function(){var uploadStatusURL="/carton/feed/get/statuses";
var feedRetentionDate=new Date()-(1000*60*60*24*85);
var shipmentIds=_(this.models).filter(function(model){return new Date(model.attributes.createDate)>feedRetentionDate;
}).map(function(model){return model.attributes.shipmentId;
});
var that=this;
$.ajax({url:uploadStatusURL,data:{shipmentIds:shipmentIds}}).done(function(response){shipmentIds.forEach(function(shipmentId){that.collection.get(shipmentId).trigger("flatFileStatus",response[shipmentId]);
});
});
},getModelMapper:function(attributeName,eventName){var that=this;
var cb=function(response){_(response.models).each(function(responseModel){var model=that.collection.get(responseModel.id);
if(model){if(!model.hasOwnProperty(attributeName)){model[attributeName]=responseModel;
model.trigger(eventName);
}}});
that.isExtraInfoRendered[attributeName]=true;
that.collection.trigger("extraInfoRender:after");
};
return cb;
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ShipmentExtraInformation=APF.View.Base.extend({initialize:function(options){this.defectsEl=this.el.find(".defects");
this.eventsEl=this.el.find(".events");
this.isSubView=options.isSubView?true:false;
this.defectsTemplate=_.template($("#fba-inbound-queue-template-shipments-extra-information-defects").html());
this.eventsTemplate=_.template($("#fba-inbound-queue-template-shipments-extra-information-events").html());
},render:function(){this.defectsEl.html(this.defectsTemplate({shipment:this.model,isSubView:this.isSubView}));
this.eventsEl.html(this.eventsTemplate({shipment:this.model,isSubView:this.isSubView}));
return this;
}});
}(jQuery));
(function($){FBA.InboundQueue.View.CLIFlatFileUploadInformation=APF.View.Base.extend({initialize:function(options){this.flatFileValidationEl=this.el.find(".flat-file-validation");
this.feedStatus=options.feedStatus;
this.model=options.model;
this.flatFileValidationTemplate=_.template($("#fba-inbound-queue-template-shipments-extra-information-flat-file-validation").html());
},render:function(){this.flatFileValidationEl.html(this.flatFileValidationTemplate({feedStatus:this.feedStatus,model:this.model}));
return this;
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ManifestCollection=APF.View.Collection.extend({view:"FBA.InboundQueue.View.Manifest",container:"#fba-inbound-queue-manifests-collection",templates:{layout:"#fba-inbound-queue-template-manifests-collection"},initialize:function(options){this.appCSM=APF.getAttr("appCSM");
this.manifestsCSM=new FBA.InboundQueue.Model.CSM();
APF.View.Collection.prototype.initialize.call(this,options);
},enter:function(events){this.collection.bind("render:after",this.trackCriticalFeature,this);
APF.View.Collection.prototype.enter.call(this,events);
},exit:function(){this.collection.unbind("render:after",this.trackCriticalFeature,this);
APF.View.Collection.prototype.exit.call(this);
},trackCriticalFeature:function(){this.appCSM.criticalFeature();
this.manifestsCSM.criticalFeature();
this.trackStop();
},trackStop:function(){this.appCSM.stop();
this.manifestsCSM.stop();
},getTemplateData:function(data,model,collection){return{data:data,dataPagination:{index:data.index||0,pageSize:collection.data.pageSize,totalRecords:collection.data.totalRecords}};
},loadCollectionData:function(){this.appCSM.start("FBA-InboundQueue-App-Manifests");
this.manifestsCSM.start("FBA-InboundQueue-Manifests");
APF.View.Collection.prototype.loadCollectionData.call(this);
},setCollectionData:function(response){this.appCSM.response();
this.manifestsCSM.response(this.collection.requestId);
APF.View.Collection.prototype.setCollectionData.call(this,response);
this.parent.options.parent.removeLoading();
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ShipmentsLayout=FBA.InboundQueue.View.Layout.extend({templateName:"#fba-inbound-queue-template-shipments-layout",controllerName:"FBA.InboundQueue.View.ShipmentsController",idAttribute:"shipmentId",initialize:function(options){this.collection=APF.getAttr("shipments");
FBA.InboundQueue.View.Layout.prototype.initialize.call(this,options);
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ManifestsController=APF.View.Controller.extend({waitForRender:true,controls:"fba-inbound-queue-controller-page",getMap:function(){var plans=APF.getAttr("plans");
var el=this.el;
if(this.state.data.page===undefined){el.find(".fba-core-data").html($("#fba-inbound-queue-content-loading").html());
el.find(".fba-core-data-pagination").html("");
plans.reset();
}return{view:"FBA.InboundQueue.View.ManifestCollection",collection:plans};
APF.View.Controller.prototype.getMap.call(this);
},initialize:function(options){this.parent=options.parent;
APF.View.Controller.prototype.initialize.call(this);
this.bind("render",this.initDateFilters,this);
},exit:function(){this.parent.removeDatePickers();
APF.View.Controller.prototype.exit.call(this);
},initDateFilters:function(){this.parent.setDateFilters();
}});
}(jQuery));
(function($){FBA.InboundQueue.View.Shipment=APF.View.Base.extend({tagName:"tr",initialize:function(options){this.isSubView=options.isSubView?true:false;
this.el=$(this.el);
this.template=_.template($("#fba-inbound-queue-template-shipments-shipment").html());
this.model.bind("defects",this.renderDetails,this);
this.model.bind("carrier",this.renderDetails,this);
this.model.bind("flatFileStatus",function(response){this.renderFlatFileStatus(response);
},this);
},render:function(){var shipment=this.model;
var isSubView=this.isSubView;
var maxPackListItemCount=APF.getAttr("maxPackListItemCount");
var packlistIndexes=_.range(0,shipment.get("totalLineItems"),maxPackListItemCount*1);
var packlists=[];
var packlistUrl=FBA.Core.Util.addReftagToUrl({url:"/gp/fba/core/templates/workflow/shipment-summary/shipment/generate-pack-list.html",reftag:{to:"fbapl",from:"fbass"}});
$.each(packlistIndexes,function(){packlists.push({index:this,url:packlistUrl});
});
this.el.html(this.template({shipment:shipment,packlists:packlists,shipmentNameUrl:shipment.getUrl({reftag:{to:"fbaisw",from:isSubView?"fbasqp":"fbasqs",where:"name"}}),shipmentButtonUrl:shipment.getUrl({reftag:{to:"fbaisw",from:isSubView?"fbasqp":"fbasqs",where:"btn"}}),isSubView:isSubView}));
var shipmentPackListEl=this.el.find(".shipment-pack-list");
if(shipmentPackListEl.length!=0){this.shipmentPackList=new FBA.Core.View.WorkflowShipmentSummaryShipmentPackList({model:this.model,el:shipmentPackListEl});
}return this;
},enter:function(){var events={"click    .fba-core-packlist-learn-more":"showMultiplePacklistHelpContent"};
Backbone.View.prototype.delegateEvents.call(this,events);
if(this.shipmentPackList){this.shipmentPackList.enter();
}},showMultiplePacklistHelpContent:function(e){e.preventDefault();
if(!this.multiplePacklistHelpPopover){this.multiplePacklistHelpPopover=new APF.View.Popover({literalContent:APF.strings["learn-more-content"],title:APF.strings["packlist-help-title"]});
}this.multiplePacklistHelpPopover.render();
},exit:function(){if(this.shipmentPackList){this.shipmentPackList.exit();
}},renderDetails:function(){var validPreorderableNotificationStatusList=APF.getAttr("validPreorderableShipmentNotificationStatusList");
var showPreorderNotification=(this.model.get("needByDate")!=null&&validPreorderableNotificationStatusList.hasOwnProperty(this.model.get("status")));
if(!this.model.hasUnacknowledgedDefect()&&!this.model.hasCarrierEvent()&&!this.model.hasMissingBOLId()&&!this.model.hasMissingTrackingId()&&!showPreorderNotification){return;
}if(!this.hasOwnProperty("extraView")){this.extraView=new FBA.InboundQueue.View.ShipmentExtraInformation({model:this.model,className:"extra-info"+(this.isSubView?" child":""),isSubView:this.isSubView,el:this.el});
}this.extraView.render();
},renderFlatFileStatus:function(response){var cliFileInfoView=new FBA.InboundQueue.View.CLIFlatFileUploadInformation({model:this.model,el:this.el});
if(response){if(response.hasFileBeenUploaded){var hasErrors=response.records&&response.records.numErrors>0;
cliFileInfoView.feedStatus=hasErrors?"FAILED":response.feedStatus;
cliFileInfoView.render();
}}else{cliFileInfoView.render();
}}});
}(jQuery));
(function($){FBA.InboundQueue.View.Manifest=APF.View.Base.extend({tagName:"tr",className:"inbound-queue-plan-item",initialize:function(){this.template=_.template($("#fba-inbound-queue-template-manifests-manifest").html());
this.el=$(this.el);
this.childIDs=0;
this.childrenToggled=false;
this.isLoading=false;
this.subViews=[];
},render:function(){var manifest=this.model;
this.el.html(this.template({manifest:manifest,manifestNameUrl:manifest.getUrl({reftag:{to:"fbaimw",from:"fbasqp",where:"name"}}),manifestButtonUrl:manifest.getUrl({reftag:{to:"fbaimw",from:"fbasqp",where:"btn"}})}));
this.loadingEl=$(".plan-loading",this.el);
this.loadingEl.hide();
return this;
},enter:function(){var events={"click .toggle-expand":"loadShipments"};
Backbone.View.prototype.delegateEvents.call(this,events);
$.each(this.subViews,function(){this.enter();
});
},getModelMapper:function(attributeName,eventName){var that=this;
var cb=function(response){_(response.models).each(function(responseModel){var model=that.model.shipments.get(responseModel.id);
if(model){if(!model.hasOwnProperty(attributeName)){model[attributeName]=responseModel;
model.trigger(eventName);
}}});
};
return cb;
},loadShipments:function(){var that=this;
this.model.fetchShipments({callback:function(){that.showSubshipments();
that.model.shipments.fetchCarrierShipments({callback:that.getModelMapper("shipmentCarrier","carrier")});
that.model.shipments.fetchDefectAcknowledgementStatus({callback:that.getModelMapper("defectStatus","defects")});
}});
if(!this.childIDs){this.loadingEl.show();
}return false;
},showSubshipments:function(){var that=this;
if(this.childIDs!=0){this.toggleChildren();
return;
}this.loadingEl.hide();
this.childIDs=this.model.cid;
this.model.shipments.each(function(ship){that.subViews.push(new FBA.InboundQueue.View.Shipment({model:ship,className:that.model.cid+" child",isSubView:true}));
});
_(this.subViews).each(function(view){$(view.render().el).insertAfter(that.el);
view.enter();
});
this.toggleChildrenClass(false);
this.childrenToggled=true;
},exit:function(){$.each(this.subViews,function(){this.exit();
});
},toggleChildren:function(){this.toggleChildrenClass(this.childrenToggled);
if(this.childrenToggled){$("."+this.childIDs).hide();
this.childrenToggled=false;
return;
}$("."+this.childIDs).show();
this.childrenToggled=true;
},toggleChildrenClass:function(childrenToggled){$(".toggle-expand",this.el).toggleClass("hide-children",childrenToggled);
$(".toggle-expand",this.el).toggleClass("show-children",!childrenToggled);
}});
}(jQuery));
(function($){FBA.InboundQueue.View.ManifestsLayout=FBA.InboundQueue.View.Layout.extend({templateName:"#fba-inbound-queue-template-manifests-layout",controllerName:"FBA.InboundQueue.View.ManifestsController",idAttribute:"manifestId",initialize:function(options){this.collection=APF.getAttr("plans");
FBA.InboundQueue.View.Layout.prototype.initialize.call(this,options);
}});
}(jQuery));
(function($){FBA.InboundQueue.View.SearchShipmentController=APF.View.Controller.extend({useData:[],initialize:function(options){this.el=$("#fba-inbound-queue-page");
APF.View.Controller.prototype.initialize.call(this,options);
},getMap:function(){return{view:"FBA.InboundQueue.View.SearchShipmentsLayout"};
}});
}(jQuery));
(function($){FBA.InboundQueue.View.SearchShipmentCollection=APF.View.Collection.extend({view:"FBA.InboundQueue.View.SearchShipment",container:"#fba-inbound-queue-search-shipments-collection",templates:{layout:"#fba-inbound-queue-template-searchshipments-collection"},getTemplateData:function(data,model,collection){return{data:data,totalQuantity:this.collection.resultCount,dataPagination:{index:data.index||0,pageSize:collection.data.pageSize,totalRecords:collection.data.resultCount}};
},setCollectionData:function(response){APF.View.Collection.prototype.setCollectionData.call(this,response);
this.parent.options.parent.removeLoading();
}});
}(jQuery));
(function($){FBA.InboundQueue.View.SearchShipmentsResultsController=APF.View.Controller.extend({waitForRender:true,controls:"fba-inbound-queue-controller-page",getMap:function(){var searchShipments=APF.getAttr("searchShipments");
var el=this.el;
el.find(".fba-core-data").html($("#fba-inbound-queue-content-loading").html());
el.find(".fba-core-data-pagination").html("");
searchShipments.reset();
return{view:"FBA.InboundQueue.View.SearchShipmentCollection",collection:searchshipments};
}});
}(jQuery));
(function($){FBA.InboundQueue.View.SearchShipmentsLayout=FBA.InboundQueue.View.Layout.extend({templateName:"#fba-inbound-queue-template-searchshipments-layout",controllerName:"FBA.InboundQueue.View.SearchShipmentsResultsController",idAttribute:"shipmentId",initialize:function(options){this.collection=APF.getAttr("searchshipments");
FBA.InboundQueue.View.Layout.prototype.initialize.call(this,options);
}});
}(jQuery));
(function($){FBA.InboundQueue.View.SearchShipment=APF.View.Base.extend({tagName:"tr",initialize:function(options){this.el=$(this.el);
this.template=_.template($("#fba-inbound-queue-template-search-shipments").html());
},render:function(){this.el.html(this.template({shipment:this.model}));
}});
}(jQuery));
